version: '3'
services:
  riverside-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      # Anonymous volume:
      - /app/node_modules

  riverside-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riverside
    ports:
      - "5433:5432"
