version: '3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: riverside
    ports:
      - "5433:5432"
